using Unity.Hierarchy;
using UnityEngine;

public class Movement2D : MonoBehaviour
{
    // Regions help visually organize your code into sections
    #region Variables
    // Headers are like titles for the Unity inspector
    [Header("Movement Variables")]

    /* In C# if you do not specify a variable modifier (i.e. public, private, protected), it defaults to private
    The private variable modifier stops other scripts from accessing those variables */
    Rigidbody2D rb;
    SpriteRenderer sprite;
    //public Animator animator;

    // I changed the SerializedFields to public so the PowerUp scripts could access them
    public float moveSpeed = 6f;
    public float jumpForce = 10f;
    public float airMoveSpeed = 6f;
    public bool isGrounded;


    //All of the double jump code comes from the video "Double Jumps, Gravity & Variable Height with Unity Input System - 2D Platformer Unity #3" by
    //Game Code Library on Youtube. Link: https://www.youtube.com/watch?v=OT537RfNzCU&t=444s
    public int maxJumps = 1;
    public int jumpsRemaining;


    bool jumpRequested; // A boolean to check if the player has requested a jump.
    float movement; // The horizontal movement of the player
    #endregion // Marks the end of the region

    #region Unity Methods
    // Start is called before the first frame update
    private void Start()
    {
        // GetComponent is used to get the component of the object this script is attached to
        sprite = GetComponent<SpriteRenderer>();
        rb = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    private void Update()
    {
        // Input.GetAxisRaw returns a float value of either -1 or 1 based on if the player is pressing left or right. It is 0 if the player is not pressing anything.
        // Use GetAxis instead if you want smooth movement with acceleration and deceleration.
        movement = Input.GetAxis("Horizontal");

        UpdateSpriteDirection();

        // If the player presses the space key, set jumpRequested to true
        if (Input.GetKeyDown(KeyCode.Space))
        {
            jumpRequested = true;

        }
        if (isGrounded) //If player is grounded, the jumps remaining is equal to the max jumps.
                        //And if the player is grounded, set the bool in the animator to false to play the fall anim.
        {
            jumpsRemaining = maxJumps;
            //animator.SetBool("IsFalling", false);

        }
        if (Input.GetKeyDown(KeyCode.Space) && jumpsRemaining == 0 && !isGrounded) //If the player is not grounded, they have no jumps left, and if they press space, they will set jump requested to false. 
                                                                                   //This fixed the problem where if the player pressed space while in air, it would set jump to true and then jump as soon as they were grounded again.
        {
            jumpRequested = false;
        }

        //animator.SetFloat("Speed", Mathf.Abs(movement));

        if (!isGrounded)
        {
            //animator.SetBool("IsFalling", true);
        }



    }
    // FixedUpdate is used for physics calculations and is called 50 times a second
    private void FixedUpdate()
    {
        // You don't need to multiply the movement by Time.deltaTime because the physics calculations are already frame-rate independent
        float currentSpeed = isGrounded ? moveSpeed : airMoveSpeed;
        rb.linearVelocity = new Vector2(movement * currentSpeed, rb.linearVelocity.y);

        Debug.Log(currentSpeed);

        // Handle the jump request
        if (jumpRequested && jumpsRemaining > 0)//If the player requests a jump and the jumpsRemaining is more than 0, call jump method
        {
            Jump();
            
        }





    }
    #endregion

    #region Custom Methods
    /// <summary>
    /// This method is used to update the sprite direction based on the player's movement
    /// </summary>
    private void UpdateSpriteDirection()
    {
        // Flips the sprite based on the direction the player is moving
        if (movement > 0f)
        {
            sprite.flipX = true;
        }
        else if (movement < 0f)
        {
            sprite.flipX = false;
        }
    }
    /// <summary>
    /// This method is used to make the player jump
    /// </summary>
    private void Jump()
    {   
        
        //Reduces the number of jumps by 1
        jumpsRemaining--;

        //If the player is not grounded and their jumps remaining are more than 0, set bool jumpRequested to false.
        if (!isGrounded && jumpsRemaining !> 0)
        {
            jumpRequested = false;
        }
        jumpRequested = false;

        // If the player is grounded and space is pressed, set the y velocity of the player to the jumpforce
        Debug.Log("Player Jumped");
        rb.linearVelocity = new Vector2(rb.linearVelocity.x, jumpForce); // Sets the y velocity of the player to the jumpforce. Preserves the x velocity.

    }

    #endregion
}